name: Label Issues (Script Injection Example)
on:
  issues:
    types:        # Specify activity types
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        # github    Context https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # Next code is bash scripting
        # |     Indicate that they are several lines of bash scripting
        run: |
          issue_title="${{ github.event.issue.title }}"
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi