name: Deployment
on:
  push:
    branches:
      - main
      - dev
# Environment variable to the steps of all jobs     https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env
env:
  MONGODB_DB_NAME: gha-demo   # key: value      Environment variable used in the code
jobs:
  test:
    environment: testing    # Specify the environment to use https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment
    # https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment
    runs-on: ubuntu-latest
    env:        # Job's environment variables --> Available to all steps in the job https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idenv
      MONGODB_CLUSTER_ADDRESS: cluster0.ntrwp.mongodb.net         # Environment variable used in the code
      # secrets   Context   https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-secrets-context
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}           # Environment variable used in the code
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}           # Environment variable used in the code
      PORT: 8080                                                  # Environment variable used in the code
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        # Get access to environment variable's value, depend on runner / OS     https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        # Getting access to environment variables via
        # 1. Depending on the runner          https://docs.github.com/en/actions/learn-github-actions/variables#detecting-the-operating-system
        # 2. env context                      https://docs.github.com/en/actions/learn-github-actions/contexts#env-context
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
          
