name: 'Deploy to AWS S3'                                # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#name
description: 'Deploy a static website via AWS S3.'      # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#description
inputs:             # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
  # Make it reusable the JS custom action
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region: 
    description: 'The region of the S3 bucket.'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'The folder containing the deployable files.'
    required: true
outputs:    # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-docker-container-and-javascript-actions
  website-url:
    description: 'The URL of the deployed website.'
    # Don't declare the value, since it's done via JS code
runs:             # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs
  # Different depending on custom action type     https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions
  using: 'node16'         # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions
  main: 'main.js'         # File with the JS code  -- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsmain